version: '3.8'

services:
  postgres:
    image: postgres:16
    container_name: aviaslaves-postgres
    restart: unless-stopped
    environment:
      POSTGRES_USER: slave
      POSTGRES_PASSWORD: slave
      POSTGRES_DB: aviaslaves
    ports:
      - "5432:5432"
    volumes:
      - aviaslaves_postgres_data:/var/lib/postgresql/data
    deploy:
      replicas: 0

  auth:
    build:
      dockerfile: Dockerfile
      context: ./Auth
    stop_signal: SIGINT
    stop_grace_period: 5s
    environment:
      DATABASE_HOST: cloud.ambassador4ik.dev
      DATABASE_PORT: 5432
      DATABASE_NAME: auth
      DATABASE_USER:
      DATABASE_PASS:
      KAFKA_URL: kafka:9092
      #BACKEND_PORT: 3001
    #depends_on:
      #- postgres
    command: ["sh", "-c", "java -jar auth.jar"]
    deploy:
      replicas: 1
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.auth-service.rule=PathPrefix(`/auth`)"
      - "traefik.http.routers.auth-service.entrypoints=web"
      - "traefik.http.services.auth-service.loadbalancer.server.port=3001"

  tickets:
    build:
      dockerfile: Dockerfile
      context: ./Tickets
    stop_signal: SIGINT
    stop_grace_period: 5s
    environment:
      DATABASE_HOST: cloud.ambassador4ik.dev
      DATABASE_PORT: 5432
      DATABASE_NAME: tickets
      DATABASE_USER:
      DATABASE_PASS:
      KAFKA_URL: kafka:9092
      # BACKEND_PORT: 3001
      #depends_on:
      #- postgres
    command: [ "sh", "-c", "java -jar tickets.jar" ]
    deploy:
      replicas: 1
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.auth-service.rule=PathPrefix(`/auth`)"
      - "traefik.http.routers.auth-service.entrypoints=web"
      - "traefik.http.services.auth-service.loadbalancer.server.port=3001"

  traefik:
    image: traefik:v3.0
    command:
      - "--api.insecure=true" # Enable Traefik dashboard
      - "--providers.docker=true"
      - "--entrypoints.web.address=:80"
    ports:
      - "80:80"   # The HTTP port
      - "8080:8080" # The Traefik dashboard port
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock:ro"
    deploy:
      replicas: 0

  zookeeper:
    image: 'bitnami/zookeeper:latest'
    logging:
      driver: none
    ports:
      - '2181:2181'
    environment:
      - ALLOW_ANONYMOUS_LOGIN=yes
    deploy:
      replicas: 1

  kafka:
    image: 'bitnami/kafka:latest'
    logging:
      driver: none
    ports:
      - '9092:9092'
    environment:
      - KAFKA_BROKER_ID=1
      - KAFKA_LISTENERS=PLAINTEXT://:9092
      - KAFKA_ADVERTISED_LISTENERS=PLAINTEXT://localhost:9092
      - KAFKA_ZOOKEEPER_CONNECT=zookeeper:2181
      - ALLOW_PLAINTEXT_LISTENER=yes
    depends_on:
      - zookeeper
    deploy:
      replicas: 1

volumes:
  aviaslaves_postgres_data: