version: '3.8'

services:
  postgres:
    image: postgres:16
    container_name: aviaslaves-postgres
    restart: unless-stopped
    environment:
      POSTGRES_USER: prisma
      POSTGRES_PASSWORD: prisma
      POSTGRES_DB: prisma
    ports:
      - "5432:5432"
    volumes:
      - aviaslaves_postgres_data:/var/lib/postgresql/data

  auth:
    build:
      dockerfile: Dockerfile
      context: ./AuthService
      args:
        NODE_ENV: production
    stop_signal: SIGINT
    stop_grace_period: 5s
    environment:
      DATABASE_URL: "postgresql://prisma:prisma@postgres:5432/authdb"
      FRONTEND_URL: "http://localhost"
      NODE_ENV: production
      BACKEND_PORT: 3001
    depends_on:
      - postgres
    entrypoint: ["/usr/src/app/scripts/init.sh"]
    command: ["bun", "run", "start"]
    deploy:
      replicas: 2
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.auth-service.rule=PathPrefix(`/auth`)"
      - "traefik.http.routers.auth-service.entrypoints=web"
      - "traefik.http.services.auth-service.loadbalancer.server.port=3001"

  traefik:
    image: traefik:v3.0
    command:
      - "--api.insecure=true" # Enable Traefik dashboard
      - "--providers.docker=true"
      - "--entrypoints.web.address=:80"
    ports:
      - "80:80"   # The HTTP port
      - "8080:8080" # The Traefik dashboard port
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock:ro"

  zookeeper:
    image: 'bitnami/zookeeper:latest'
    ports:
      - '2181:2181'
    environment:
      - ALLOW_ANONYMOUS_LOGIN=yes
  kafka:
    image: 'bitnami/kafka:latest'
    ports:
      - '9092:9092'
    environment:
      - KAFKA_BROKER_ID=1
      - KAFKA_LISTENERS=PLAINTEXT://:9092
      - KAFKA_ADVERTISED_LISTENERS=PLAINTEXT://localhost:9092
      - KAFKA_ZOOKEEPER_CONNECT=zookeeper:2181
      - ALLOW_PLAINTEXT_LISTENER=yes
    depends_on:
      - zookeeper

volumes:
  aviaslaves_postgres_data: